= Source Code
:page-editable: true
:sectnums:

== Use Cases

The following use cases will be shown:

* Default usage with default theme: `nord`
* Change default theme to `darcula` in `Antora` playbook
* Change theme on page level
* Change theme on single source block
* Enable line numbers on source block
* Enable line numbers on all pages
* Enable line numbers on specific page
* Disable line numbers on source block
* Disable line numbers on specific page

=== Default usage with default theme: nord

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension' #<1>
----
<1> test

=== Default usage with default theme: nord and callouts

.Antora Playbook
[source,yaml,theme=github-light]
----
antora:
  extensions:
    - 'antora-shiki-extension' #<1>

asciidoc:
  attributes:
    source-highlighter: shiki #<2>
----
<1> Register the antora extension
<2> Set the source-highlighter to shiki
<3> test

.Result
[source,javascript]
-------
include::example$javascript.js[]
-------

=== Change default theme to `darcula` in `Antora` playbook

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
      theme: 'dracula'
----

.Result
[source,javascript,theme=dracula]
----
include::example$javascript.js[]
----

=== Change theme on page level

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
----

.Page level theme definition
[source,asciidoc]
----
= Page Title
:shiki-theme: dracula
----

.Result
[source,javascript,theme=dracula]
----
include::example$javascript.js[]
----

=== Change theme on single source block

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
----

.Page level theme definition
[source,asciidoc]
-------
[source,javascript,theme=dracula]
----
function helloWorld() {
  console.log('Hello World');
}
----
-------

.Result
[source,javascript,theme=dracula]
----
include::example$javascript.js[]
----

=== Enable line numbers on source block

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
----

[source,asciidoc]
-------
[source,javascript,linenums]
----
function helloWorld() {
  console.log('Hello World');
}
----
-------

.Result
[source,javascript,linenums]
-------
include::example$javascript.js[]
-------

=== Enable line numbers on specific page

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
----

[source,asciidoc]
----
= Page Title
:shiki-line-numbers: true
----

.Result
[source,javascript,linenums]
-------
include::example$javascript.js[]
-------

You can also unset it via `!shiki-line-numbers:` like the theme.

=== Enable line numbers on all pages

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
      use_line_numbers: true
----

=== Disable line numbers on single source block

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
      use_line_numbers: true
----

[source,asciidoc]
-------
[source,javascript,nolinenums]
----
function helloWorld() {
  console.log('Hello World');
}
----
-------

.Result
[source,javascript,nolinenums]
-------
include::example$javascript.js[]
-------

=== Disable line numbers on specific page

[source,asciidoc]
----
= Page Title
:shiki-line-numbers: false
----

=== Line numbers with specific beginning

.Antora Playbook
[source,yaml]
----
antora:
  extensions:
    - require: 'antora-shiki-extension'
----

[source,asciidoc]
-------
[source,javascript,linenums,start=2]
----
function helloWorld() {
  console.log('Hello World');
}
----
-------

.Result
[source,javascript,linenums,start=2]
-------
include::example$javascript.js[]
-------

